import React from "react";
import { AIQuestionRaw } from "./types";

interface AIApprovalModalProps {
  showAIApprovalModal: boolean;
  pendingAIQuestions: AIQuestionRaw[];
  onClose: () => void;
  onApproveAIQuestion: (questionData: object) => Promise<void>;
  onRejectAIQuestion: (index: number) => void;
  loadingQuestions: boolean;
}

export default function AIApprovalModal({
  showAIApprovalModal,
  pendingAIQuestions,
  onClose,
  onApproveAIQuestion,
  onRejectAIQuestion,
  loadingQuestions,
}: AIApprovalModalProps) {
  if (!showAIApprovalModal || pendingAIQuestions.length === 0) return null;

  const formatOptionText = (text: string) => {
    return text
      .replace(/^[a-dA-D]\)\s*/, "")
      .replace(/^[a-dA-D]\.\s*/, "")
      .replace(/^[a-dA-D]\s*-\s*/, "")
      .trim();
  };

  const parseOptions = (optionsText: string | string[]) => {
    if (Array.isArray(optionsText)) {
      return optionsText.map((option) => formatOptionText(option));
    }
    const lines = optionsText.split("\n").filter((line) => line.trim());
    return lines.map((line) => formatOptionText(line));
  };

  const findCorrectAnswer = (
    optionsText: string | string[],
    correctAnswerText: string | number,
  ) => {
    const options = parseOptions(optionsText);
    const cleanCorrectAnswer = formatOptionText(String(correctAnswerText));

    for (let i = 0; i < options.length; i++) {
      if (
        options[i].toLowerCase().includes(cleanCorrectAnswer.toLowerCase()) ||
        cleanCorrectAnswer.toLowerCase().includes(options[i].toLowerCase())
      ) {
        return i;
      }
    }
    return 0;
  };

  const handleApprove = async (aiQuestion: AIQuestionRaw, index: number) => {
    const questionData = {
      text: aiQuestion.question,
      type: aiQuestion.type,
      maxMarks: aiQuestion.maxMarks || 1,
      options:
        aiQuestion.type === "MULTIPLE_CHOICE"
          ? parseOptions(aiQuestion.options || "")
          : undefined,
      correctAnswer:
        aiQuestion.type === "MULTIPLE_CHOICE"
          ? findCorrectAnswer(
              aiQuestion.options || "",
              aiQuestion.correctAnswer || "",
            )
          : aiQuestion.type === "TRUE_FALSE"
            ? String(aiQuestion.correctAnswer || "").toLowerCase() === "true"
              ? 0
              : 1
            : undefined,
    };

    await onApproveAIQuestion(questionData);
    onRejectAIQuestion(index);
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-md flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-3xl w-full max-w-4xl shadow-2xl overflow-hidden max-h-[90vh] overflow-y-auto">
        <div className="px-8 py-6 bg-gradient-to-r from-blue-500 to-indigo-600 sticky top-0 z-10">
          <h3 className="text-2xl font-bold text-white">
            AI Generated Questions ({pendingAIQuestions.length})
          </h3>
          <p className="text-blue-100 mt-1">
            Review and approve questions generated by AI
          </p>
        </div>

        <div className="p-6 space-y-6">
          {pendingAIQuestions.map((aiQuestion, index) => (
            <div
              key={index}
              className="border-2 border-gray-200 rounded-2xl p-6 hover:border-blue-300 transition-all"
            >
              <div className="mb-4">
                <div className="flex items-center justify-between mb-2">
                  <span className="px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-sm font-medium">
                    {aiQuestion.type === "MULTIPLE_CHOICE"
                      ? "Multiple Choice"
                      : aiQuestion.type === "TRUE_FALSE"
                        ? "True/False"
                        : aiQuestion.type === "SHORT_ANSWER"
                          ? "Short Answer"
                          : "Long Answer"}
                  </span>
                  <span className="text-sm text-gray-500">
                    Max Marks: {aiQuestion.maxMarks || 1}
                  </span>
                </div>
                <h4 className="text-lg font-semibold text-gray-900 mb-3">
                  {aiQuestion.question}
                </h4>
              </div>

              {aiQuestion.type === "MULTIPLE_CHOICE" && aiQuestion.options && (
                <div className="mb-4">
                  <h5 className="font-medium text-gray-700 mb-2">Options:</h5>
                  <div className="space-y-2">
                    {parseOptions(aiQuestion.options).map(
                      (option, optIndex) => {
                        const isCorrect =
                          findCorrectAnswer(
                            aiQuestion.options || "",
                            aiQuestion.correctAnswer || "",
                          ) === optIndex;
                        return (
                          <div
                            key={optIndex}
                            className={`p-3 rounded-lg border ${
                              isCorrect
                                ? "bg-green-50 border-green-200 text-green-800"
                                : "bg-gray-50 border-gray-200"
                            }`}
                          >
                            <span className="font-medium">
                              {String.fromCharCode(65 + optIndex)}.
                            </span>{" "}
                            {option}
                            {isCorrect && (
                              <span className="ml-2 text-green-600 font-bold">
                                ✓ Correct
                              </span>
                            )}
                          </div>
                        );
                      },
                    )}
                  </div>
                </div>
              )}

              {aiQuestion.type === "TRUE_FALSE" && (
                <div className="mb-4">
                  <h5 className="font-medium text-gray-700 mb-2">
                    Correct Answer:
                  </h5>
                  <div className="flex gap-4">
                    <div
                      className={`p-3 rounded-lg border ${
                        String(aiQuestion.correctAnswer || "").toLowerCase() ===
                        "true"
                          ? "bg-green-50 border-green-200 text-green-800"
                          : "bg-gray-50 border-gray-200"
                      }`}
                    >
                      True{" "}
                      {String(aiQuestion.correctAnswer || "").toLowerCase() ===
                        "true" && (
                        <span className="text-green-600 font-bold">✓</span>
                      )}
                    </div>
                    <div
                      className={`p-3 rounded-lg border ${
                        String(aiQuestion.correctAnswer || "").toLowerCase() ===
                        "false"
                          ? "bg-green-50 border-green-200 text-green-800"
                          : "bg-gray-50 border-gray-200"
                      }`}
                    >
                      False{" "}
                      {String(aiQuestion.correctAnswer || "").toLowerCase() ===
                        "false" && (
                        <span className="text-green-600 font-bold">✓</span>
                      )}
                    </div>
                  </div>
                </div>
              )}

              {(aiQuestion.type === "SHORT_ANSWER" ||
                aiQuestion.type === "LONG_ANSWER") &&
                aiQuestion.correctAnswer && (
                  <div className="mb-4">
                    <h5 className="font-medium text-gray-700 mb-2">
                      Sample Answer:
                    </h5>
                    <div className="p-3 bg-green-50 border border-green-200 rounded-lg text-green-800">
                      {aiQuestion.correctAnswer}
                    </div>
                  </div>
                )}

              <div className="flex gap-3 pt-4 border-t border-gray-200">
                <button
                  onClick={() => onRejectAIQuestion(index)}
                  disabled={loadingQuestions}
                  className="flex-1 px-4 py-3 bg-red-100 text-red-700 font-medium rounded-xl hover:bg-red-200 transition-all disabled:opacity-50"
                >
                  Reject
                </button>
                <button
                  onClick={() => handleApprove(aiQuestion, index)}
                  disabled={loadingQuestions}
                  className="flex-1 px-4 py-3 bg-gradient-to-r from-green-500 to-emerald-500 text-white font-bold rounded-xl hover:from-green-600 hover:to-emerald-600 transition-all shadow-lg hover:shadow-xl disabled:opacity-50"
                >
                  {loadingQuestions ? "Adding..." : "Approve & Add"}
                </button>
              </div>
            </div>
          ))}

          <div className="flex gap-3 pt-4 border-t border-gray-200">
            <button
              onClick={onClose}
              className="flex-1 px-6 py-4 bg-gray-100 text-gray-700 font-bold rounded-xl hover:bg-gray-200 transition-all text-lg"
            >
              Close
            </button>
            <button
              onClick={() => {
                // Reject all remaining questions
                for (let i = pendingAIQuestions.length - 1; i >= 0; i--) {
                  onRejectAIQuestion(i);
                }
                onClose();
              }}
              disabled={loadingQuestions}
              className="flex-1 px-6 py-4 bg-red-500 text-white font-bold rounded-xl hover:bg-red-600 transition-all text-lg disabled:opacity-50"
            >
              Reject All
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
